
FROM ruby:3.0.2

WORKDIR /app
ADD Gemfile /app/Gemfile
#ADD Gemfile.lock /app/Gemfile.lock
RUN gem install bundler
RUN bundle install
RUN bundle update --bundler
ADD . /app
# RUN bundle install
RUN bundle update --bundler
RUN bundle install


EXPOSE 8080

#CMD ["ruby", "helloworld.rb"]
#CMD ["rackup"]
CMD ["rackup", "--host", "0.0.0.0", "-p", "8080"]

# https://github.com/tongueroo/sinatra/blob/master/Dockerfile

